### ISSUE TITLE
fix service file

### ISSUE THREAD

**Issue by lilydjwg** [cookiengineer/dns-proxy#1]
You'd like to remove the `ExecStop=` line because it doesn't work. And if it worked, it might kill too many processes.

FYI here's mine: https://github.com/lilydjwg/dns-tcp-socks-proxy/blob/master/arch_files/tcpdnsproxy.service

BTW, there are too many issues in this project (I've reported a few), e.g. it segfaults when `/etc/dns_proxy/resolv.conf` contains only one line.

**Comment by cookiengineer** [comment]
Yes, the segfault regarding one line is fixed, it was related to the `NUM_DNS - 1` part and I explicitely merged that in from somewhere else (can't remember, too many fixes merged already :D).

Thanks for the hint with the service file, I'm gonna fix that.

**Comment by cookiengineer** [comment]
Yep, service file is fixed. I had to set the `User=root` because the default configuration will listen on port 53, but it's up and working on my two machines here.

```bash
[$] sudo systemctl status dns-proxy
● dns-proxy.service - Transparent DNS SOCKS Proxy
   Loaded: loaded (/usr/lib/systemd/system/dns-proxy.service; disabled; vendor preset: disabled)
   Active: active (running) since Wed 2018-07-04 11:00:02 CEST; 4s ago
 Main PID: 16673 (dns-proxy)
    Tasks: 1 (limit: 4915)
   Memory: 228.0K
   CGroup: /system.slice/dns-proxy.service
           └─16673 /usr/bin/dns-proxy /etc/dns-proxy/dns-proxy.conf

Jul 04 11:00:02 weep systemd[1]: Started Transparent DNS SOCKS Proxy.
```

Again, thanks much for the hint. Let me know if you find other problems or reopen when this is not fixed ^_^
